### PR TITLE
Fix for some languages IPA not populating

### PR DESCRIPTION
**Pull request by syntheticgio**
Made a few changes that might be desirable to merge into the master branch:
1. Fix for Spanish not populating properly 
2. Added a config.md with descriptions on the config options
3. Added a config option to be able to maintain the '.' in IPA.  Default is same behavior it currently is
4. Added language options: italian, portuguese, chinese (simplified), and catalan.

### CODE REVIEW

**Comment by peter-moran** [comment]
How can I package this to try in Anki?

**Comment by soliviantar** [comment]
@peter-moran @syntheticgio I tried installing this by downloading the zip file from [here](https://github.com/syntheticgio/anki-ipa/tree/fix-not-populating-translation) and installing the add-on manually, following [these instructions](https://github.com/glutanimate/anki-addons-misc). However, it didn't work. It threw this error:

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨anki_ipa⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\gecru\AppData\Roaming\Anki2\addons21\anki_ipa\__init__.py", line 60
    ipa = parse_ipa_transcription.transcript(words=words, language=lang_alias, CONFIG["STRIP_SYLLABLE_SEPARATOR"])
                                                                                                                 ^
SyntaxError: positional argument follows keyword argument

**Review by schorlus — APPROVED** [review]
Great work, thanks!

**Review by m-rtin — APPROVED** [review]

**Comment by m-rtin** [comment]
I updated the add-on on Anki web with the changes you made. I removed the languages you added again though since they were not working probably. Feel free to add them again in another PR with proper unit-testing :)

**Pull request merged**
